# Generated by Django 2.0 on 2019-03-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0025_auto_20190311_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCourseStartTimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='设置开课时间')),
                ('course_obj', models.ForeignKey(help_text='要为哪个课程设置开课时间', on_delete=django.db.models.deletion.CASCADE, to='main.CourseModel')),
                ('school_obj', models.ForeignKey(help_text='要在哪个学校设置课程的开课时间', on_delete=django.db.models.deletion.CASCADE, to='main.SchoolModel')),
            ],
        ),
    ]
