# Generated by Django 2.0 on 2019-03-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190311_1006'),
        ('schoolmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolcoursestarttimemodel',
            unique_together={('school_obj', 'course_obj')},
        ),
    ]
