# Generated by Django 2.0 on 2019-03-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190311_1006'),
        ('schoolmanager', '0002_auto_20190311_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDegreeStartTimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='设置章节的开课时间')),
                ('degree_obj', models.ForeignKey(help_text='要为哪个章节设置开课时间', on_delete=django.db.models.deletion.CASCADE, to='main.CourseDegreeModel')),
                ('school_obj', models.ForeignKey(help_text='要在哪个学校设置章节的开课时间', on_delete=django.db.models.deletion.CASCADE, to='main.SchoolModel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schooldegreestarttimemodel',
            unique_together={('school_obj', 'degree_obj')},
        ),
    ]
