# Generated by Django 2.0 on 2019-03-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190311_1006'),
        ('schoolmanager', '0003_auto_20190311_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CourseModel')),
                ('student_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StudentModel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schoolcoursestarttimemodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='schoolcoursestarttimemodel',
            name='course_obj',
        ),
        migrations.RemoveField(
            model_name='schoolcoursestarttimemodel',
            name='school_obj',
        ),
        migrations.DeleteModel(
            name='SchoolCourseStartTimeModel',
        ),
        migrations.AlterUniqueTogether(
            name='studentcoursemodel',
            unique_together={('student_obj', 'course_obj')},
        ),
    ]
