# Generated by Django 2.0 on 2019-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errormodel',
            name='response_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
