# Generated by Django 2.0 on 2019-02-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0002_errormodel_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormodel',
            name='response_status',
            field=models.IntegerField(help_text='响应状态'),
        ),
    ]
