# Generated by Django 2.0 on 2019-03-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0007_exceptionlogmodel_exception_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceptionlogmodel',
            old_name='URL',
            new_name='url',
        ),
    ]
