# Generated by Django 2.0 on 2019-03-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0008_auto_20190307_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionlogmodel',
            name='cookie_data',
            field=models.BinaryField(help_text='被转化为文本的cookie的数据'),
        ),
        migrations.AlterField(
            model_name='exceptionlogmodel',
            name='exception_data',
            field=models.BinaryField(help_text='记录异常的提示信息'),
        ),
        migrations.AlterField(
            model_name='exceptionlogmodel',
            name='get_data',
            field=models.BinaryField(help_text='被转化为文本的get的数据'),
        ),
        migrations.AlterField(
            model_name='exceptionlogmodel',
            name='header_data',
            field=models.BinaryField(help_text='被转化为文本的header的数据'),
        ),
        migrations.AlterField(
            model_name='exceptionlogmodel',
            name='post_data',
            field=models.BinaryField(help_text='被转化为文本的post的数据'),
        ),
    ]
