# Generated by Django 2.0 on 2019-03-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0010_auto_20190307_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlogmodel',
            name='action',
            field=models.CharField(help_text='请求方式', max_length=10, null=True),
        ),
    ]
