# Generated by Django 2.0 on 2019-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0011_exceptionlogmodel_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlogmodel',
            name='status',
            field=models.CharField(help_text='状态码', max_length=10, null=True),
        ),
    ]
