# Generated by Django 2.0 on 2019-03-06 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassStudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClassModel')),
                ('user_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDegreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(default='2019-01-31T17:43:49.944376+08:00')),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('school_name', models.CharField(max_length=50)),
                ('city_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CityModel')),
                ('user_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_data_at', models.DateField(auto_now=True, help_text='创建日期')),
                ('red_card', models.IntegerField(default=0)),
                ('blue_card', models.IntegerField(default=0)),
                ('yellow_card', models.IntegerField(default=0)),
                ('course_comment', models.TextField(default='')),
                ('stage_comment', models.TextField(default='')),
                ('study', models.BooleanField(default=True)),
                ('edit_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ClassModel')),
                ('school_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SchoolModel')),
                ('user_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ManyToManyField(to='main.ClassModel')),
                ('school_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SchoolModel')),
                ('user_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='student_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StudentModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='school_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SchoolModel'),
        ),
        migrations.AddField(
            model_name='coursedegreemodel',
            name='course_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CourseModel'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='school_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SchoolModel'),
        ),
        migrations.AddField(
            model_name='classcoursemodel',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClassModel'),
        ),
        migrations.AddField(
            model_name='classcoursemodel',
            name='course_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CourseModel'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='province_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProvinceModel'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolmodel',
            unique_together={('school_name', 'city_obj')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodel',
            unique_together={('school_obj', 'course_name')},
        ),
        migrations.AlterUniqueTogether(
            name='classmodel',
            unique_together={('school_obj', 'class_name')},
        ),
        migrations.AlterUniqueTogether(
            name='classcoursemodel',
            unique_together={('class_obj', 'course_obj')},
        ),
    ]
