# Generated by Django 2.0 on 2019-03-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190306_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='created_data_at',
        ),
    ]
