# Generated by Django 2.0 on 2019-03-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_studentinfomodel_created_data_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='edit_status',
        ),
    ]
