# Generated by Django 2.0 on 2019-03-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190306_1958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageschoolmodel',
            unique_together={('school_obj', 'comment_time')},
        ),
    ]
