# Generated by Django 2.0 on 2019-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190306_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='blue_card',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='course_comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='red_card',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='stage_comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='yellow_card',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
