# Generated by Django 2.0 on 2019-03-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190307_1249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinfomodel',
            unique_together={('created_data_at', 'student_obj')},
        ),
    ]
