# Generated by Django 2.0 on 2019-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190307_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BinaryField()),
            ],
        ),
    ]
