# Generated by Django 2.0 on 2019-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190308_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnoticemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='创建时间'),
        ),
    ]
