# Generated by Django 2.0 on 2019-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190308_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnoticemodel',
            name='send_start_date',
            field=models.DateField(help_text='通知的开始时间'),
        ),
    ]
