# Generated by Django 2.0 on 2019-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190308_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnoticemodel',
            name='send_end_date',
            field=models.DateTimeField(help_text='通知的结束时间'),
        ),
        migrations.AlterField(
            model_name='classnoticemodel',
            name='send_start_date',
            field=models.DateTimeField(help_text='通知的开始时间'),
        ),
    ]
