# Generated by Django 2.0 on 2019-03-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190311_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfomodel',
            name='class_name',
            field=models.CharField(help_text='记录这条信息时,学生所在的班级', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='degree',
            field=models.CharField(help_text='记录这条信息时,学生的课程进度', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='start_time',
            field=models.CharField(help_text='记录这条信息时,学生的开课时间', max_length=30, null=True),
        ),
    ]
