# Generated by Django 2.0 on 2019-03-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190311_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfomodel',
            old_name='start_time',
            new_name='study_time',
        ),
    ]
