# Generated by Django 2.0 on 2019-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190311_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedegreemodel',
            name='start_at',
        ),
        migrations.AddField(
            model_name='coursedegreemodel',
            name='degree_name',
            field=models.CharField(help_text='章节的名字', max_length=50, null=True),
        ),
    ]
