# Generated by Django 2.0 on 2019-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190311_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedegreemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coursedegreemodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='coursedegreemodel',
            name='remark',
            field=models.TextField(help_text='章节的备注信息', null=True),
        ),
    ]
