# Generated by Django 2.0 on 2019-03-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190311_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedegreemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursedegreemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
