# Generated by Django 2.0 on 2019-03-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190311_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedegreemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
