# Generated by Django 2.0 on 2019-03-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190312_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfomodel',
            name='course_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CourseModel'),
        ),
    ]
