# Generated by Django 2.0 on 2019-03-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_studentinfomodel_course_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfomodel',
            old_name='course_obj',
            new_name='course_obj_log',
        ),
    ]
