# Generated by Django 2.0 on 2019-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190312_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='course_comment',
            field=models.TextField(default='', null=True),
        ),
    ]
